RB-4 React Router, integration with API
rimakan/react-burger pull request #4
Opened 2023-10-22 07:29 UTC by rimakan

2023-10-22 07:57 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая работа с формами
- Есть автологин
- Настроены все редиректы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Не авторизованный юзер не должен иметь возможность сделать заказ
- После авторизации инпуты где должны находится данные юзера - пустые. Если уйти и вернутся на страницу профиля - инпуты заполняются. 

<img width="701" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/9e8603bc-91ef-4d51-8521-a6a551199977">

- Если изменить на странице профиля какие-то данные в инпутах, но не трогать пароль, то он всё равно попадает в payload запроса в виде - "******". Необходимо отправлять на сервер только те поля, которые были изменены.

<img width="1440" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/9498cecf-ef86-45fa-af1e-61f1b925020b">

- PATCH запрос изменения данных юзера возвращает новые данные, не нужно после него делать ещё и GET запрос
- При запросах, использующих `accessToken`, должен проверятся ответ сервера. Если время жизни токена истекло, то необходимо выполнить запрос обновления токена и повторить запрос, который не был выполнен успешно. Воспроизвести проблему можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

Для этого используйте обертку над fetch, примерно такую

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

- роут `/reset-password` не должен быть доступен напрямую

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-10-22 07:57 UTC, andryxxa93 commented on src/components/App/App.tsx
> +          <Route path="/login" element={<LoginPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-10-22 07:57 UTC, andryxxa93 commented on src/components/Common/NavigationLink/NavigationLink.tsx
> +const NavigationLink: React.FC<NavigationLinkProps> = ({ to, children, isActive, className, onClick }) => {
**Можно лучше**
Чтобы не создавать отдельный компонент, можно использовать NavLink из библиотеки react-router. 
https://reactrouter.com/en/main/components/nav-link

2023-10-22 07:57 UTC, andryxxa93 commented on src/components/Common/Routes/PrivateRoute/PrivateRoute.tsx
> +  return (user || token) &&
**Можно лучше**
наличие токена ещё не значит, что он будет принят сервером, поэтому правильно при прямом переходе на защищенную страницу даже при наличии токена следует отправлять запрос на сервер (например запрос получения данных пользователя) и только если запрос будет выполнен и токен принят, можно отображать защищенную страницу

На время выполнения этого запроса проверяющего актуальность токена нужно отображать прелоадер, а при завершении запроса в случае успеха отображать защищенный компонент, а в случае ошибки - очищать токен и перенаправлять на страницу входе

2023-10-23 10:56 UTC, rimakan commented on src/components/Common/NavigationLink/NavigationLink.tsx
> +const NavigationLink: React.FC<NavigationLinkProps> = ({ to, children, isActive, className, onClick }) => {
спасибо, я знаю о нем, но мне было проще таким образом, потому что мой вариант поддерживает isActive и я могу подсвечивать ссылки при переходе на них

2023-10-24 06:00 UTC, andryxxa93 commented
**Необходимо исправить**
- Если не авторизованный юзер пытается сделать заказ его перекидывать на страницу логина и после авторизации обратно, но при попытке сделать заказ этот процесс повторяется. Скорее всего дело в том, что после прохождения запроса /login в стор хранилища не записывается объект данных юзера, хотя запрос его возвращает.
<img width="443" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/8a0aaca8-f7fd-43a2-968a-2e10428f2e95">

2023-10-24 07:24 UTC, rimakan commented
> **Необходимо исправить**
> 
> * Если не авторизованный юзер пытается сделать заказ его перекидывать на страницу логина и после авторизации обратно, но при попытке сделать заказ этот процесс повторяется. Скорее всего дело в том, что после прохождения запроса /login в стор хранилища не записывается объект данных юзера, хотя запрос его возвращает.
> 
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/60173362/277562192-8a0aaca8-f7fd-43a2-968a-2e10428f2e95.png">

fixed, thank you

2023-10-24 15:45 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-24 16:03 UTC, merged