RB-6 WS support, new screens
rimakan/react-burger pull request #6
Opened 2023-11-19 16:00 UTC by rimakan

2023-11-19 16:40 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Хорошая типизация redux
- Данные получаемые по веб-сокету хранятся в отдельных местах стора
- Реализован универсальный веб-сокет

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Очень много повторяющихся запросов ингредиентов при переходе на страницу Ленты заказов
<img width="1434" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/fd31a200-683c-498a-ac4b-62d17f20884c">
- Сокеты необходимо открывать только при переходе на страницы "Лента заказов" и "История заказов".
- Сокеты необходимо закрывать сразу после ухода со страниц "Лента заказов" и "История заказов".

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-19 16:40 UTC, andryxxa93 commented on src/api/WsClient.ts
> +        this.socket.onmessage = (event: MessageEvent) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-11-19 16:40 UTC, andryxxa93 commented on src/api/WsClient.ts
> +  public close(): void {
**Можно лучше**
Так как браузерный веб-сокет не обладает возможностью переподключения из-за обрыва соединения - желательно это делать самому через setTiimeout

2023-11-19 17:47 UTC, rimakan commented on src/api/WsClient.ts
> +        this.socket.onmessage = (event: MessageEvent) => {
у меня API миддлвар обновляет токены, если они протухают

2023-11-20 09:57 UTC, andryxxa93 commented
**Необходимо исправить**
- Проблема с большим количеством запросов при переходе на Ленту Заказов осталась
<img width="1439" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/87701669-9a73-4b38-9593-71cdd2c438bd">
- Теперь при переходе по прямой ссылке на какой-то заказ - вечный лоадер. 
<img width="1440" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/f492efa0-5634-4e55-9f94-927b57c5a7f4">

2023-11-23 11:14 UTC, andryxxa93 commented
**Необходимо исправить**
- Проект не собирается из-за отсутствия файла с функцией
<img width="998" alt="image" src="https://github.com/rimakan/react-burger/assets/60173362/7d7c5608-bb49-48a7-8e9a-3505aec64f35">

2023-11-24 13:39 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-24 18:24 UTC, merged